databases:
  - name: webapps2023
    databaseName: webapps2023
    user: webapps2023

services:
  - type: web
    name: webapps2023
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn webapps2023.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webapps2023
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4