# Generated by Django 4.1.7 on 2023-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_remove_transaction_from_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2015-10-10 20:20:33'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
